[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kvali = "2TWg6cMa7bxFa8y7HHoDXZecNJxcbYrUAqwfrg5T8FPK"

[programs.localnet]
kvali = "2TWg6cMa7bxFa8y7HHoDXZecNJxcbYrUAqwfrg5T8FPK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
